# Generated by Django 6.0 on 2026-01-28 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(default='1317920625', max_length=20)),
                ('telefono', models.CharField(default='0980643265', max_length=20)),
                ('origen', models.CharField(default='Manta, EC', max_length=100)),
                ('estado_civil', models.CharField(default='Soltero', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Datos Personales',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('periodo', models.CharField(help_text='Ej: Ene 2026 - Actualidad', max_length=100)),
                ('funciones', models.TextField()),
                ('estado', models.CharField(choices=[('En curso', 'En curso'), ('Finalizado', 'Finalizado')], default='Finalizado', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Experiencia Laboral',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Bruno Fernando Macias Moreira', max_length=200)),
                ('email', models.EmailField(default='Franyo678@gmail.com', max_length=254)),
                ('phone', models.CharField(default='0980643265', max_length=20)),
                ('location', models.CharField(default='Jocay j4 y j9, Manta, Ecuador', max_length=200)),
                ('summary', models.TextField(default='Profesional de sala con experiencia en restaurantes...')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
