# Generated by Django 6.0.1 on 2026-02-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='estado_civil',
            field=models.CharField(default='Soltero', max_length=50),
        ),
    ]
