# Generated by Django 6.0 on 2026-01-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_datospersonales_experiencialaboral_habilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.DeleteModel(
            name='DatosPersonales',
        ),
        migrations.DeleteModel(
            name='ExperienciaLaboral',
        ),
    ]
