# Generated by Django 6.0 on 2026-01-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_curso_proyectogarage_reconocimiento_delete_habilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectogarage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='garage/'),
        ),
        migrations.AddField(
            model_name='proyectogarage',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='proyectogarage',
            name='tecnologias',
            field=models.CharField(help_text='Ej: Hardware, Gadget', max_length=200),
        ),
    ]
