# Generated by Django 5.1.4 on 2026-02-02 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_alter_curso_archivo_extra_alter_curso_vista_previa'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='cv.perfil', verbose_name='Perfil Asociado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cv.perfil', verbose_name='Perfil Asociado'),
        ),
        migrations.AddField(
            model_name='educacion',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='cv.perfil', verbose_name='Perfil Asociado'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.perfil', verbose_name='Perfil Asociado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_venta', to='cv.perfil', verbose_name='Vendedor (Perfil)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='cv.perfil', verbose_name='Perfil Asociado'),
        ),
    ]
