# Generated by Django 5.1.4 on 2026-02-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_experiencia_archivo_experiencia_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='educacion/archivos/', verbose_name='Archivo Adjunto (PDF)'),
        ),
        migrations.AddField(
            model_name='educacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='educacion/logos/', verbose_name='Logo Institución'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='proyectos/archivos/', verbose_name='Archivo Adjunto (PDF)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/logos/', verbose_name='Logo Proyecto/Cliente'),
        ),
    ]
