# Generated by Django 6.0.1 on 2026-02-03 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_educacion_archivo_educacion_logo_proyecto_archivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='archivo_extra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='cv.perfil'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='pdf_archivo',
            field=models.FileField(upload_to='cursos/pdfs/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cv.perfil'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='vista_previa',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/previews/'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='educacion/archivos/'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='educacion/logos/'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='cv.perfil'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='experiencia/archivos/'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='experiencia/logos/'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='Buen Estado', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_venta', to='cv.perfil'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='proyectos/archivos/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/logos/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='cv.perfil'),
        ),
    ]
